### PR TITLE
chore: update examples to latest sdk version

### PR DESCRIPTION
**Pull request by yhl25**

### CODE REVIEW

**Review by vigith — COMMENTED** [review]
Why didn't we use local path reference in go.mod for examples?

**Comment by vigith** [comment]
> Why didn't we use local path reference in go.mod for examples?

@KeranYang do you remember?

**Review by vigith — APPROVED** [review]
Looks like we still have to give version

**Comment by KeranYang** [comment]
@vigith we declare in `go,mod` required version of numaflow-go, but when building the `stable` image, we use the local reference. We don't necessarily need to update the version but I am ok with making it up-to-date. cc: @ayildirim21

**Pull request merged**
